### ISSUE TITLE
"load from json" feature

### ISSUE THREAD

**Issue by vladlinhg** [zackhxn/openpose-hand-editor#1]
Have you considered adding or implementing the "load from json" option?
I have checked the json output from this editor and it will produce 60 check points in json file, which won't lead to %18 === 0
I have stopped from there after I have altered the value from %18 === 0 to % 12 === 0, since it still gives me back the alert.

That's a great idea to come up with this extension, if the feature may be implemented without error, I believe it will be a lot more popular.

Thank you!

**Comment by zackhxn** [comment]
Thanks for your suggestion! Both [Load from JSON] and [Save JSON] are now available to use.You can use a structure like
 {
    "width": 512,
    "height": 512,
    "keypoints": [
        [
            239,
            75
        ],
        [
            239,
            118
        ],
        [
            189,
            116
        ],
        [
            175,
            181
        ],
        [
            161,
            250
        ],
        [
            296,
            116
        ],
        [
            315,
            180
        ],
        [
            330,
            243
        ],
        [
            223,
            239
        ],
        [
            211,
            357
        ],
        [
            213,
            452
        ],
        [
            268,
            238
        ],
        [
            280,
            358
        ],
        [
            284,
            454
        ],
        [
            230,
            57
        ],
        [
            251,
            58
        ],
        [
            223,
            68
        ],
        [
            258,
            70
        ]
    ],
    "hands_keypoints": [
        [
            332,
            246
        ],
        [
            336,
            233
        ],
        [
            344,
            218
        ],
        [
            352,
            207
        ],
        [
            359,
            198
        ],
        [
            365,
            228
        ],
        [
            378,
            220
        ],
        [
            388,
            215
        ],
        [
            396,
            211
        ],
        [
            367,
            238
        ],
        [
            385,
            231
        ],
        [
            395,
            226
        ],
        [
            404,
            224
        ],
        [
            366,
            246
        ],
        [
            383,
            241
        ],
        [
            393,
            240
        ],
        [
            403,
            238
        ],
        [
            364,
            253
        ],
        [
            375,
            252
        ],
        [
            382,
            252
        ],
        [
            389,
            252
        ],
        [
            159,
            254
        ],
        [
            151,
            240
        ],
        [
            138,
            227
        ],
        [
            128,
            216
        ],
        [
            119,
            206
        ],
        [
            122,
            239
        ],
        [
            107,
            234
        ],
        [
            97,
            231
        ],
        [
            87,
            227
        ],
        [
            120,
            249
        ],
        [
            103,
            245
        ],
        [
            92,
            243
        ],
        [
            83,
            241
        ],
        [
            122,
            259
        ],
        [
            106,
            257
        ],
        [
            95,
            256
        ],
        [
            85,
            256
        ],
        [
            126,
            268
        ],
        [
            115,
            268
        ],
        [
            107,
            268
        ],
        [
            100,
            267
        ]
    ]
}
to load ,the saved json format will also look like this.

**Comment by vladlinhg** [comment]
Thank you for updating the repo!

I think the issue is solved!, Nice work!
